route:
    receiver: 'slack'
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Prometheus'
            channel: '#random'
            api_url: 'https://hooks.slack.com/services/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'