version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.3.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - alertmanager
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  grafana:
    image: grafana/grafana:4.6.3
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
  alertmanager:
    image: prom/alertmanager:v0.15.2
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'
    ports:
      - "9093:9093"