global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

rule_files:
  - './rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093